name: その他
description: 質問や相談など
title: "[質問] "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: 内容
      description: 聞きたいことや相談内容を書いてください
      placeholder: 例: サーバーに導入する方法を知りたい
    validations:
      required: true
